#!/bin/python
import sys
import copy

class Exp:
    def __init__(self, *args):
        self.op = args[0]
        self.operands = list()
        for operand in args[1:]:
            self.operands.append(operand)

    def __str__(self):
        if len(self.operands) == 1:
            return self.op + str(self.operands[0]) 
        else:
            result = "(" + str(self.operands[0])
        for i in range(1,len(self.operands)):
            result = result + " " + self.op + " " + str(self.operands[i])
        result = result + ")"
        return result
    def eval(self, values, prevValues):
        if self.op == 'd':
            return values[self.operands[0]] - prevValues[self.operands[0]]
        elif self.op == 'v':
            return self.operands[0]
        elif self.op == 'p':
            return values[self.operands[0]]
        
        left = values[self.operands[0]] if type(self.operands[0]) is tuple else self.operands[0].eval(values, prevValues)
        right = values[self.operands[1]] if type(self.operands[1]) is tuple else self.operands[1].eval(values, prevValues)
        if self.op == '*':
            return left * right
        elif self.op == '/':
            return left / right
        elif self.op == '^':
            return left ^ right
        elif self.op == '+':
            return left + right
        elif self.op == '-':
            return left - right
    def calcDerivation(self):
        if self.op == 'p':
            dSelf = copy.deepcopy(self)
            dSelf.op = 'd'
            return dSelf
        elif self.op == 'd':
            dSelf = copy.deepcopy(self)
            dSelf.op = 'dd'
            return dSelf
        elif self.op == 'v':
            return Exp('v', 0)
        elif self.op == '*':
            return Exp('+', Exp('*', self.operands[0].calcDerivation(), self.operands[1]), Exp('*', self.operands[0], self.operands[1].calcDerivation()))
        elif self.op == '+' or self.op == '-':
            return Exp(self.op, self.operands[0].calcDerivation(), self.operands[1].calcDerivation())
        elif self.op == '/':
            return Exp('/', 
                    Exp('-', 
                        Exp('*', 
                            self.operands[0].calcDerivation() , 
                            self.operands[1] ) , 
                        Exp('*', 
                            self.operands[0], 
                            self.operands[1].calcDerivation() 
                            ) 
                        ), 
                    Exp('^', self.operands[1], Exp('v', 2))
                    )




previousValues = {}
currentValues = {}
estimatedNextValues = {}

def V_t(pair):
    return currentValues[pair]

def dV_t(pair):
    return currentValues[pair] - previousValues[pair]

def V_tplus1(pair):
    return estimatedNextValues[pair]

def SetEstimated_V_tplus1(pair, value):
    estimatedNextValues[pair] = value

def dV_tplus1(pair):
    return estimatedNextValues[pair] - currentValues[pair]

def SetEstimated_dV_tplus1(pair, dvalue):
    estimatedNextValues[pair] = dvalue + currentValues[pair]

def initValues(eq):
    for pair in eq[0]:
        previousValues[pair] = float(input("Enter open value for " + str(pair) + " : "))
        currentValues[pair] = float(input("Enter close value for " + str(pair) + " : "))

    for pair in eq[1]:
        previousValues[pair] = float(input("Enter open value for " + str(pair) + " : "))
        currentValues[pair] = float(input("Enter close value for " + str(pair) + " : "))

def setInitialEstimates(eq):
    for pair in currentValues:
        estimatedNextValues[pair] = 2 * currentValues[pair] - previousValues[pair]

def refineEstimates(eq):
    for pair in currentValues:
        f = formula(pair, eq)
        df = f.calcDerivation()
        df_tplus1 = evalFormulaWithEstimatedValues(df)
        estimatedNextValues[pair] = df_tplus1

def parseEquation(left, right):
    leftPairStrs = left.split('*')
    rightPairStrs = right.split('*')
    resultEquation = ([],[])
    for p in leftPairStrs:
        pt, pb = p.split("/")
        resultEquation[0].append((pt,pb))
    for p in rightPairStrs:
        pt, pb = p.split("/")
        resultEquation[1].append((pt,pb))
    return resultEquation

def formula(estmtPair, eq):
   # check if (top/buttom) is on top of eq
   if estmtPair in eq[0]:
       newEq = ([],[])
       for pair in eq[1]:
           newEq[0].append(pair)
       for pair in eq[0]:
           if pair != estmtPair:
               newEq[1].append(pair)
       return eq2Exp(newEq)
   # check buttom
   if estmtPair in eq[1]:
       newEq = ([],[])
       for pair in eq[0]:
           newEq[0].append(pair)
       for pair in eq[1]:
           if pair != estmtPair:
               newEq[1].append(pair)
       return eq2Exp(newEq)
   return None

def eq2Exp(eq):
    if len(eq[0]) == 0:
        return Exp('/', Exp('v', 1), listMultiplication2Exp(eq[1]))
    elif len(eq[1]) == 0:
        return listMultiplication2Exp(eq[0])
    return Exp('/', listMultiplication2Exp(eq[0]), listMultiplication2Exp(eq[1]))

def listMultiplication2Exp(pairList):
    if len(pairList) == 1:
        return Exp('p', pairList[0])
    print(pairList)
    return Exp('*', Exp('p', pairList[0]), listMultiplication2Exp(pairList[1:]))

def evalFormulaWithEstimatedValues(formula):
    pass

if __name__=="__main__":
    print("Hello World!!!")
#    for line in sys.stdin:
#        print(line)
    left = input("Enter the left side of the equation: ")
    #left = "A/B*C/D"
    #left = "A/B*C/D*G/R"
    right = input("Enter the right side of the equation: ")
    #right = "Q/W"
    #right = "Q/W*I/O"
    #req = input("Enter pair to see formula: ")
    #req = "Q/W"
    eq = parseEquation(left, right)
    initValues(eq)
    setInitialEstimates(eq)
    for i in range(1,1000):
        refineEstimates(eq)

    for k, v in estimatedNextValues.items():
        print(str(k) + "  ==>  " + str(v) )
    #reqFormula = formula((req.split('/')[0], req.split('/')[1]), eq)
    #reqDFormula = reqFormula.calcDerivation()
    #print("Pair Formula:")
    #print(reqFormula)
    #print("Pair Derivation Formula:")
    #print(reqDFormula)
